### ISSUE TITLE
Prison Jobs Broken

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#62] opened 2023-04-03 07:39 UTC
Prison jobs for reduction in time are broken. Waypoint is made but when prompted for the job, it does not let you do anything.

---
This issue was created by `@MNightDieALittle` in `#server-issues`.

**Comment by urban-z** [comment] 2023-04-11 01:22
@dexslab --> This is confirmed for the cleaning jobs only.  Electrician work appropriately.  So does regular CS.  However, script is encrypted and unable to diagnosis issue since I can only see the locales and config files which appear to be in working order

**Comment by dexslab** [comment] 2023-04-11 01:25
You can take a look at the jobs in the jobs config look for gabz then the cleaning job there I most likely screwed up the config

**Comment by urban-z** [comment] 2023-04-11 02:52
sv-jobs is where it is stored, however, it is encrypted.

**Comment by dexslab** [comment] 2023-04-11 03:37
No it's stored in the config files because by default it doesn't have time reduction for gabz prison stuff I added it by hand.

**Comment by urban-z** [comment] 2023-04-11 03:38
Just found the issue after messing with a bit. I am working to fix it right now :)

**Comment by urban-z** [comment] 2023-04-11 22:16
@dexslab  --> Fix has been placed in DEV and pull request is ready for merge to Master.  I have disabled the credit jobs and enabled reduced sentence only until RCORE makes update

**Closed** 2023-04-15 21:12 UTC
Labels: bug, Confirmed, Script Issue, Resolved
