### ISSUE TITLE
Commuinty Service

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#173] opened 2023-06-17 03:19 UTC
So whenever doing the jobs it's outlinded in orange and for my last one it wasn't there and I couldn't request a new job. I asked staff they didn't know and I think Alan had the same problem. I looked everywhere in the circle and I couldn't find it at all after looking for about 5-10 mins, AFTER all the jobs were done.

---
This issue was created by `@NOODLE` in `#server-issues`.

**Comment by urban-z** [comment] 2023-06-29 05:11
Duplicate of #164

**Closed by urban-z** 2023-06-29 05:11 UTC
Labels: bug, Script Issue, Unconfirmed
